### ISSUE TITLE
Bring Speedtest back from CAutomator Legacy

### ISSUE THREAD

**Issue by SuperTux20** [Hyperfresh/CAutomator#56]

**Comment by Hyperfresh** [comment]
Found an NPM package for speedtest: https://www.npmjs.com/package/speedtest-net. `npm i speedtest-net`

@SuperTux20, if you'd like to look at the library and perhaps make a PR on it, that'd be appreciated c:
If you can't, don't worry, I'll still add the feature when I have the time.
